doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: UTF8
        mapping_types:
            enum: string

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Bundle\Driver:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Bundle/Driver/Entity'
                prefix: 'App\Bundle\Driver\Entity'
                alias: App\Bundle\Driver
            App\Bundle\Import:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Bundle/Import/Entity'
                prefix: 'App\Bundle\Import\Entity'
                alias: App\Bundle\Import
            App\Bundle\ImportDelivery:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Bundle/ImportDelivery/Entity'
                prefix: 'App\Bundle\ImportDelivery\Entity'
                alias: App\Bundle\ImportDelivery
            App\Bundle\ImporterGenerator:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Bundle/ImporterGenerator/Entity'
                prefix: 'App\Bundle\ImporterGenerator\Entity'
                alias: App\Bundle\ImporterGenerator
            App\Bundle\User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Bundle/User/Entity'
                prefix: 'App\Bundle\User\Entity'
                alias: App\Bundle\User
            App\Bundle\Perception:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Bundle/Perception/Entity'
                prefix: 'App\Bundle\Perception\Entity'
                alias: App\Bundle\Perception
            App\Bundle\Route:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Bundle/Route/Entity'
                prefix: 'App\Bundle\Route\Entity'
                alias: App\Bundle\Route
            App\Bundle\TopCity:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Bundle/TopCities/Entity'
                prefix: 'App\Bundle\TopCities\Entity'
                alias: App\Bundle\TopCity
