doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            App\Bundle\Import:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Bundle/Import/Entity'
                prefix: 'App\Bundle\Import\Entity'
                alias: App\Bundle\Import
            App\Bundle\ImportDelivery:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Bundle/ImportDelivery/Entity'
                prefix: 'App\Bundle\ImportDelivery\Entity'
                alias: App\Bundle\ImportDelivery
            App\Bundle\ImporterGenerator:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Bundle/ImporterGenerator/Entity'
                prefix: 'App\Bundle\ImporterGenerator\Entity'
                alias: App\Bundle\ImporterGenerator
            App\Bundle\User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Bundle/User/Entity'
                prefix: 'App\Bundle\User\Entity'
                alias: App\Bundle\User`
