version: "3.7"

services:
  nginx:
    image: nginx:1.17
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/etc/nginx/mime.types:/etc/nginx/mime.types
      - ./docker/etc/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build:
      context: .
      args:
        PROJECT_DIR: /var/www
    environment:
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASS}
      RABBIT_VHOST: ${RABBIT_VHOST}
      RABBIT_ADDRESS_QUEUE_COUNT: ${RABBIT_ADDRESS_QUEUE_COUNT}
      USER: ${USER}
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www
      - ./docker/usr/local/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/usr/local/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - rabbit
      - mysql

  rabbit:
    image: rabbitmq:3.8.6-management-alpine
    hostname: "rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5673:5672"
      - "15673:15672"

  mysql:
    image: 'mysql:5.7'
    restart: 'always'
    expose:
      - '3306'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  tensorflow:
    hostname: "tensorflow"
    command: "python -m http.server 8888"
    build:
      context: .
      dockerfile: ./Dockerfile-tensorflow
    ports:
      - '8888:8888'
    volumes:
      - ./tensorflow:/var/www
    depends_on:
      - mysql
