controllers:
    resource: ../../src/Controller/
    type: annotation

import_delivery:
    resource: ../../src/Bundle/ImportDelivery/Controller/

kernel:
    resource: ../../src/Kernel.php
    type: annotation
